In [2]:
import numpy as np
np.array([1,2,3])


array([1, 2, 3])

In [3]:
np.array([[1,2,3],[4,5,6]])


array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.arange(1,11)#create specific range array


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
d=np.arange(1,11,2)#crete specific range array with skip
print(d)

[1 3 5 7 9]


In [6]:
np.arange(1,11).reshape(5,2)#reshape into 5x2 metrics 


array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
np.arange(32).reshape(2,2,2,2,2)

array([[[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]],



       [[[[16, 17],
          [18, 19]],

         [[20, 21],
          [22, 23]]],


        [[[24, 25],
          [26, 27]],

         [[28, 29],
          [30, 31]]]]])

In [8]:
np.ones([3,4])#create array for only ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros([3,4])#create Array for only zeros 


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.random.random([3,4])#create random array 


array([[0.16885   , 0.15146673, 0.33362387, 0.39222617],
       [0.63461715, 0.22090077, 0.43994184, 0.08055379],
       [0.35856258, 0.98258342, 0.85222455, 0.57813648]])

In [11]:
np.linspace(-10,10,10)#first argument is lower range second is upper range and last one is how many number you want to generate
#it generte equidistence point


array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [12]:
np.identity(5,dtype=int)#create an identity array and defualt is float,dtype convert into any type 

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [13]:
a1=np.arange(11)#1D array
a2=np.arange(16,dtype=float).reshape(4,4)#2D array
a3=np.arange(27).reshape(3,3,3)#3D array


In [14]:
a1.ndim#give the n dimension

1

In [15]:
a2.ndim

2

In [16]:
a3.ndim

3

In [17]:
a1.shape#give the shape of a metrics

(11,)

In [18]:
a2.shape

(4, 4)

In [19]:
a3.shape

(3, 3, 3)

In [20]:
a1.size#give total number of element in an array

11

In [21]:
a2.size


16

In [22]:
a3.size

27

In [23]:
a1.itemsize#give the size of each item in bytes

4

In [24]:
a2.itemsize

8

In [25]:
a1.dtype #give the data type of items in an array

dtype('int32')

In [26]:
a2.dtype

dtype('float64')

In [27]:
a3.dtype



dtype('int32')

In [28]:
a3.astype('int64')#convert a data type into another data type 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]], dtype=int64)

In [29]:
b1=np.arange(12).reshape(3,4)
b2=np.arange(12,24).reshape(3,4)


In [30]:
b1


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
b1*2#multiple with every item,we can use every single arithmtic operations like(*,+,-,**,%)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [32]:
b2>5#compare with each item set and return true or false

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
b1+b2 #sum two metrix 

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [35]:
b1-b2



array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [36]:
b1*b2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [37]:
c1=np.arange(1,10).reshape(3,3)

In [38]:
c1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
np.max(c1)#maximum item

9

In [43]:
np.max(c1,axis=0)#column wise Max 

array([7, 8, 9])

In [44]:
np.max(c1,axis=1)#row wise Max

array([3, 6, 9])

In [40]:
np.min(c1)#minimum item

1

In [41]:
np.sum(c1)#sum of every item

45

In [45]:
np.sum(c1,axis=1)#row wise sum

array([ 6, 15, 24])

In [42]:
np.prod(c1)#product of every item 

362880

In [47]:
np.mean(c1)#mean for whole metrix

5.0

In [48]:
np.mean(c1,axis=0)#column wise mean

array([4., 5., 6.])

In [49]:
np.median(c1)#meadian for whole metrix

5.0

In [50]:
np.median(c1,axis=1)#row wise median

array([2., 5., 8.])

In [51]:
np.std(c1)#standered deviation for whole metrix

2.581988897471611

In [53]:
np.var(c1)#veriance for whole metrix

6.666666666666667

In [56]:
np.sin(c1)#trignometric functions same for all cos ,cot,ten...

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [77]:
np.log(c1)#log for each item

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [76]:
np.exp(c1)#exponet for each item

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [66]:
d1=np.arange(1,10).reshape(3,3)
d2=np.arange(10,19).reshape(3,3)

In [69]:
d1,d2



(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]))

In [72]:
np.dot(d1,d2)#dot product

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [79]:
e1=np.random.random((5,2))
e1

array([[0.89186954, 0.35610585],
       [0.10059632, 0.10112236],
       [0.24134418, 0.16822062],
       [0.11204771, 0.82246408],
       [0.21407715, 0.53308199]])

In [83]:
np.round(e1)#round of numbers

array([[1., 0.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [0., 1.]])

In [86]:
np.floor(e1)#giving floor value

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [87]:
np.ceil(e1)#giving ceiling value

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [88]:
f1=np.arange(1,10)
f2=np.arange(1,10).reshape(3,3)
f3=np.arange(1,9).reshape(2,2,2)

In [90]:
f1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
f1[4],f1[0]#giving index alue

(5, 1)

In [96]:
f1[0:5]#giving the range 5 index exclude

array([1, 2, 3, 4, 5])

In [97]:
f1[0:8:2]#skiping one element

array([1, 3, 5, 7])

In [98]:
f2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
f2[0,2]#with row and column index we can find the element

3

In [105]:
f2[::2,::2]#giving all corners

array([[1, 3],
       [7, 9]])

In [109]:
f2[1:,1:3]

array([[5, 6],
       [8, 9]])

In [112]:
f3


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [113]:
f3[1,1,0]#part,row,column

7

In [116]:
g1=np.arange(10)
g2=np.arange(8).reshape(2,2,2)

In [115]:
for i in g1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [120]:
for i in np.nditer(g2):#np.nditer convert Nd to 1d and print
    print(i)

0
1
2
3
4
5
6
7


In [123]:
g3=np.arange(1,10).reshape(3,3)
g3


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
np.transpose(g3)#transpose the matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [129]:
g3.ravel()#convert nd to 1D array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
g2.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [130]:
h1=np.arange(12).reshape(3,4)
h2=np.arange(12,24).reshape(3,4)
h3=np.arange(24,36).reshape(3,4)

In [132]:
np.hstack((h1,h2))#stack item hrizontaly 3x4 and 3x4=3x8

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [133]:
np.vstack((h1,h2))#stack verticaly 3x4 and 3x4 =6x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [135]:
np.hsplit(h1,2)#split horizontaly in half or any possible part 3x4=3x2 and 3x2

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [138]:
np.vsplit(h1,3)#split verticaly in half or any possible part 3x4=1x4,1x4and1x4

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]